# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to 5.3.8
  - 5.3
  # aliased to 5.4.0RC6
  - 5.4
env:
  - DB=sqlite

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer --dev install

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit.xml.dist --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "pc.bertineau@alterphp.com"
